site_name: flagd
theme:
  name: material
  palette: 
      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/logo-white.svg
  favicon: assets/logo-white.svg
  icon:
    repo: fontawesome/brands/github
  features:
  #  - navigation.tabs
   - content.action.edit
   - content.code.copy

docs_dir: web-docs
repo_url: https://github.com/open-feature/flagd
repo_name: open-feature/flagd
edit_uri: edit/main/web-docs/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      # linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - 'Getting started': 'index.md'
  - 'Concepts':
    - 'Feature Flagging': 'concepts/feature-flagging.md'
    - 'OpenFeature Compliance': 'concepts/openfeature-compliance.md'
    - 'Syncs': 'concepts/syncs.md'
  - 'Architecture': 'architecture.md'
  - 'Deployment': 'deployment.md'
  - 'Reference':
    - 'flagd CLI':
      - 'flagd Commands': 'reference/flagd-cli/flagd.md'
      - '"start" Command': 'reference/flagd-cli/flagd_start.md'
      - '"version" Command': 'reference/flagd-cli/flagd/flagd_version.md'
    - 'Sync Configuration': 'reference/sync-configuration.md'
    - 'Flag Configuration':
      - 'Configuration Overview': 'reference/flag-configuration.md'
      - 'Custom Operations':
        - 'Fractional': 'reference/custom-operations/fractional.md'
        - 'String Comparison': 'reference/custom-operations/string-comparision.md'
        - 'Semantic Version Comparison': 'reference/custom-operations/semver-comparison.md'
    - 'Flag Evaluation Protocol': 'reference/flag-evaluation-protocol.md'
    - 'Flag Sync Protocol': 'reference/flag-sync-protocol.md'
    - 'Providers': 'reference/providers.md'
    - 'Monitoring': 'reference/monitoring.md'
  - 'FAQ': 'faq.md'
  - 'Troubleshooting': 'troubleshooting.md'
plugins:
  - social