site_name: flagd
site_description: A feature flag daemon with a Unix philosophy
theme:
  name: material
  palette: 
      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode
  logo: assets/logo-white.svg
  favicon: assets/logo-white.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.footer
    - content.action.edit
    - content.code.copy
    - search.suggest
    - search.highlight
    - search.share
    - content.tooltips
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
extra_css:
  - assets/extra.css

docs_dir: docs
repo_url: https://github.com/open-feature/flagd
repo_name: open-feature/flagd
edit_uri: edit/main/docs/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      # linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - 'Introduction': 'index.md'
  - 'Quick start': 'quick-start.md'
  - 'Installation': 'installation.md'
  - 'Playground': 'playground/index.md'
  - 'Concepts':
    - 'Feature Flagging': 'concepts/feature-flagging.md'
    - 'Syncs': 'concepts/syncs.md'
    - 'Selectors': 'concepts/selectors.md'
  - 'Architecture': 'architecture.md'
  - 'Guides':
    - 'Migrating to Flag Sets': 'guides/migrating-to-flag-sets.md'
  - 'OpenFeature Providers':
    - 'providers/index.md'
    - 'Go': 'providers/go.md'
    - 'Java': 'providers/java.md'
    - 'Node.JS': 'providers/nodejs.md'
    - 'PHP': 'providers/php.md'
    - '.NET': 'providers/dotnet.md'
    - 'Python': 'providers/python.md'
    - 'Rust': 'providers/rust.md'
    - 'Web': 'providers/web.md'
  - 'Reference':
    - 'CLI':
      - 'Overview': 'reference/flagd-cli/flagd.md'
      - 'Start': 'reference/flagd-cli/flagd_start.md'
      - 'Version': 'reference/flagd-cli/flagd_version.md'
    - 'Sync Configuration': 'reference/sync-configuration.md'
    - 'Selector Syntax': 'reference/selector-syntax.md'
    - 'gRPC sync service': 'reference/grpc-sync-service.md'
    - 'OFREP service': 'reference/flagd-ofrep.md'
    - 'Flag Definitions':
      - 'Definition Overview': 'reference/flag-definitions.md'
      - 'Custom Operations':
        - 'Fractional': 'reference/custom-operations/fractional-operation.md'
        - 'Semantic Version': 'reference/custom-operations/semver-operation.md'
        - 'String Comparison': 'reference/custom-operations/string-comparison-operation.md'
      - 'Schema': 'reference/schema.md'
    - 'Monitoring': 'reference/monitoring.md'
    - 'Specifications':
      - 'Providers': 'reference/specifications/providers.md'
      - 'Protobuf Schemas': 'reference/specifications/protos.md' 
      - 'Custom Operations':
        - 'Fractional Specification': 'reference/specifications/custom-operations/fractional-operation-spec.md'
        - 'Semantic Version Specification': 'reference/specifications/custom-operations/semver-operation-spec.md'
        - 'String Comparison Specification': 'reference/specifications/custom-operations/string-comparison-operation-spec.md'
    - 'OpenFeature Operator': 'reference/openfeature-operator/overview.md'
    - 'Naming': 'reference/naming.md'
  - 'FAQ': 'faq.md'
  - 'Troubleshooting': 'troubleshooting.md'
plugins:
  # Disabling social until https://github.com/squidfunk/mkdocs-material/issues/6983 is resolved
  # - social
  - search
  # https://github.com/mondeja/mkdocs-include-markdown-plugin
  - include-markdown
  # https://github.com/mkdocs/mkdocs-redirects
  - redirects:
      redirect_maps:
        'reference/providers.md': 'providers/index.md'
        'reference/openfeature-operator/installation.md': 'https://github.com/open-feature/open-feature-operator/blob/main/docs/installation.md'
        'reference/openfeature-operator/crds/featureflag.md': 'https://github.com/open-feature/open-feature-operator/blob/main/docs/feature_flag.md'
        'reference/openfeature-operator/crds/featureflagsource.md': https://github.com/open-feature/open-feature-operator/blob/main/docs/feature_flag_source.md
        'reference/specifications/rpc-providers.md': 'reference/specifications/providers.md#rpc-providers'
        'reference/specifications/in-process-providers.md': 'reference/specifications/providers.md#in-process-providers'
