site_name: flagd
site_description: A feature flag daemon with a Unix philosophy
theme:
  name: material
  palette: 
      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/logo-white.svg
  favicon: assets/logo-white.svg
  icon:
    repo: fontawesome/brands/github
  features:
  #  - navigation.tabs
   - content.action.edit
   - content.code.copy

docs_dir: web-docs
repo_url: https://github.com/open-feature/flagd
repo_name: open-feature/flagd
edit_uri: edit/main/web-docs/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      # linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - attr_list
  - pymdownx.emoji:
      # we are using an older emoji extension because the newest (suggested in docs) doesn't work with Python < 3.10
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - 'Getting started': 'index.md'
  - 'Concepts':
    - 'Feature Flagging': 'concepts/feature-flagging.md'
    - 'Syncs': 'concepts/syncs.md'
  - 'Architecture': 'architecture.md'
  - 'Deployment': 'deployment.md'
  - 'Reference':
    - 'flagd CLI':
      - 'flagd Commands': 'reference/flagd-cli/flagd.md'
      - '"start" Command': 'reference/flagd-cli/flagd_start.md'
      - '"version" Command': 'reference/flagd-cli/flagd/flagd_version.md'
    - 'Sync Configuration': 'reference/sync-configuration.md'
    - 'Flag Definition':
      - 'Definition Overview': 'reference/flag-definition.md'
      - 'Custom Operations':
        - 'Fractional': 'reference/custom-operations/fractional-operation.md'
        - 'Semantic Version': 'reference/custom-operations/semver-operation.md'
        - 'String Comparison': 'reference/custom-operations/string-comparison-operation.md'
    - 'Providers': 'reference/providers.md'
    - 'Monitoring': 'reference/monitoring.md'
    - 'Specifications':
      - 'RPC Providers': 'reference/specifications/rpc-providers.md'
      - 'In-Process Providers': 'reference/specifications/in-process-providers.md'
      - 'Protobuf schemas': 'reference/specifications/protos.md' 
      - 'Custom Operations':
        - 'Fractional Specification': 'reference/specifications/custom-operations/fractional-operation-spec.md'
        - 'Semantic Version Specification': 'reference/specifications/custom-operations/semver-operation-spec.md'
        - 'String Comparison Specification': 'reference/specifications/custom-operations/string-comparison-operation-spec.md'
    - 'Naming': 'reference/naming.md'
  - 'FAQ': 'faq.md'
  - 'Troubleshooting': 'troubleshooting.md'
plugins:
  - social
