name: "Trigger Site Rebuild on a CRON Schedule"

on:
  schedule:
    # runs at 02:00 every day, UTC
    - cron: "0 2 * * *"

jobs:
  benchmark-publish:
    name: Run Benchmark
    if: github.repository == 'open-feature/flagd'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: "1.19.3"
      - name: Run benchmark
        run: go test -bench . -benchtime=5s -benchmem ./... | tee output.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Go Benchmark
          tool: "go"
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
