name: "Trigger Site Rebuild on a CRON Schedule"

on:
  schedule:
    # runs at 02:00 every day, UTC
    - cron: "0 2 * * *"

env:
  GO_VERSION: 1.19.3

jobs:
  benchmark-publish:
    name: Run Benchmark
    if: github.repository == 'open-feature/flagd'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3

      - name: Setup go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run benchmark
        run: set -o pipefail; go test -bench=Bench -short -benchtime=5s -benchmem ./core/... | tee output.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Go Benchmark
          tool: "go"
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
